(ns sprog.dev.startup
  (:require sprog.dev.fbm-demo))

(defn init []
  #_(sprog.dev.basic-demo/init)
  #_(sprog.dev.multi-texture-output-demo/init)
  #_(sprog.dev.fn-sort-demo/init)
  #_(sprog.dev.pixel-sort-demo/init)
  #_(sprog.dev.raymarch-demo/init)
  #_(sprog.dev.physarum-demo/init)
  #_(sprog.dev.texture-channel-demo/init)
  #_(sprog.dev.struct-demo/init)
  #_(sprog.dev.simplex-demo/init)
  #_(sprog.dev.tilable-simplex-demo/init)
  #_(sprog.dev.macro-demo/init)
  #_(sprog.dev.bilinear-demo/init)
  #_(sprog.dev.vertex-demo/init)
  #_(sprog.dev.voronoise-demo/init)
  #_(sprog.dev.video-demo/init)
  #_(sprog.dev.webcam-demo/init)
  #_(sprog.dev.bloom-demo/init)
  #_(sprog.dev.texture-3d-demo/init)
  #_(sprog.dev.gaussian-demo/init)
  #_(sprog.dev.hsv-demo/init)
  #_(sprog.dev.params-demo/init)
  #_(sprog.dev.gabor-demo/init)
  #_(sprog.dev.oklab-mix-demo/init)
  (sprog.dev.fbm-demo/init))

(defn pre-init []
  (js/window.addEventListener "load" (fn [_] (init))))
